Repository JavierAybar/Recipe-app, pull requests merged in 2023-11, with the labels that each got.

#16 Install Devise
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  app/controllers/users_controller.rb
  app/models/user.rb
  app/views/devise/confirmations/new.html.erb
  app/views/devise/mailer/confirmation_instructions.html.erb
  app/views/devise/mailer/email_changed.html.erb
  app/views/devise/mailer/password_change.html.erb
  app/views/devise/mailer/reset_password_instructions.html.erb
  app/views/devise/mailer/unlock_instructions.html.erb
  app/views/devise/passwords/edit.html.erb
  app/views/devise/passwords/new.html.erb
  app/views/devise/registrations/edit.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/devise/shared/_error_messages.html.erb
  app/views/devise/shared/_links.html.erb
  app/views/devise/unlocks/new.html.erb
  app/views/layouts/application.html.erb
  app/views/recipes/index.html.erb
  app/views/users/_form.html.erb
  app/views/users/_user.html.erb
  app/views/users/_user.json.jbuilder
  app/views/users/edit.html.erb
  app/views/users/index.html.erb
  app/views/users/index.json.jbuilder
  app/views/users/new.html.erb
  app/views/users/show.html.erb
  app/views/users/show.json.jbuilder
  config/environments/development.rb
  config/initializers/devise.rb
  config/locales/devise.en.yml
  config/routes.rb
  db/migrate/20231113170127_add_devise_to_users.rb
  db/schema.rb
Labels: day 0

#17 Recipe list
  app/controllers/recipes_controller.rb
  app/views/recipes/index.html.erb
  app/views/recipes/show.html.erb
  config/routes.rb
Labels: enhancement

#18 Adding Food table
  app/controllers/foods_controller.rb
  app/views/foods/_food.html.erb
  app/views/foods/_food.json.jbuilder
  app/views/foods/_form.html.erb
  app/views/foods/edit.html.erb
  app/views/foods/index.html.erb
  app/views/foods/index.json.jbuilder
  app/views/foods/new.html.erb
  app/views/foods/show.html.erb
  app/views/foods/show.json.jbuilder
  app/views/users/index.html.erb
  app/views/users/show.html.erb
  config/routes.rb
  db/migrate/20231113155707_create_foods.rb
  db/schema.rb
Labels: day 0

#19 Recipes details
  app/controllers/recipes_controller.rb
  app/models/recipe.rb
  app/views/recipes/show.html.erb
  config/routes.rb
  db/schema.rb
Labels: enhancement

#20 Adding Public recipes views
  app/controllers/recipe_foods_controller.rb
  app/controllers/recipes_controller.rb
  app/views/foods/new.html.erb
  app/views/recipe_foods/_form.html.erb
  app/views/recipe_foods/_recipe_food.html.erb
  app/views/recipe_foods/_recipe_food.json.jbuilder
  app/views/recipe_foods/edit.html.erb
  app/views/recipe_foods/index.html.erb
  app/views/recipe_foods/index.json.jbuilder
  app/views/recipe_foods/new.html.erb
  app/views/recipe_foods/show.html.erb
  app/views/recipe_foods/show.json.jbuilder
  app/views/recipes/_form.html.erb
  app/views/recipes/_recipe.html.erb
  app/views/recipes/_recipe.json.jbuilder
  app/views/recipes/edit.html.erb
  app/views/recipes/index.html.erb
  app/views/recipes/index.json.jbuilder
  app/views/recipes/new.html.erb
  app/views/recipes/public.html.erb
  app/views/recipes/show.html.erb
  app/views/recipes/show.json.jbuilder
  config/routes.rb
  db/migrate/20231113161555_create_recipes.rb
  db/schema.rb
Labels: day 1

#22 Fixing n+1 errors
  Gemfile
  Gemfile.lock
  app/controllers/recipes_controller.rb
  app/views/recipes/show.html.erb
  config/environments/development.rb
Labels: day 2

#23 Adding Integration test
  .rspec
  Gemfile
  Gemfile.lock
  app/models/recipe.rb
  app/models/user.rb
  app/views/recipes/show.html.erb
  spec/models/user_spec.rb
  spec/rails_helper.rb
  spec/spec_helper.rb
  spec/system/foods_index_spec.rb
  spec/system/recipes_index_spec.rb
  spec/system/recipes_public_spec.rb
  spec/system/recipes_show_spec.rb
  spec/system/spec_support_helpers.rb
Labels: day 2

#24 Adding Navigation
  app/views/foods/_navigation.html.erb
  app/views/foods/index.html.erb
  app/views/foods/new.html.erb
  app/views/recipe_foods/_navigation.html.erb
  app/views/recipe_foods/new.html.erb
  app/views/recipes/_navigation.html.erb
  app/views/recipes/index.html.erb
  app/views/recipes/new.html.erb
  app/views/recipes/public.html.erb
  app/views/recipes/show.html.erb
  app/views/shopping_lists/_navigation.html.erb
  app/views/shopping_lists/index.html.erb
Labels: day 2

#25 Unit test
  spec/requests/foods_spec.rb
  spec/requests/recipes_spec.rb
Labels: enhancement

#26 Styles
  .gitignore
  Gemfile
  Gemfile.lock
  Procfile.dev
  app/assets/builds/.keep
  app/assets/config/manifest.js
  app/assets/stylesheets/application.css
  app/assets/stylesheets/application.tailwind.css
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/devise/shared/_links.html.erb
  app/views/foods/_navigation.html.erb
  app/views/foods/index.html.erb
  app/views/foods/new.html.erb
  app/views/layouts/application.html.erb
  app/views/recipe_foods/_navigation.html.erb
  app/views/recipe_foods/new.html.erb
  app/views/recipes/_navigation.html.erb
  app/views/recipes/index.html.erb
  app/views/recipes/new.html.erb
  app/views/recipes/public.html.erb
  app/views/recipes/show.html.erb
  app/views/shared/_navigation.html.erb
  app/views/shopping_lists/_navigation.html.erb
  app/views/shopping_lists/index.html.erb
  bin/dev
  config/tailwind.config.js
  spec/system/foods_index_spec.rb
Labels: enhancement
